### ISSUE TITLE
Xcode 13 issue - Enum cases with associated values cannot be marked potentially unavailable with '@available' 

### ISSUE THREAD

**Issue by rizwan95** [SwiftKickMobile/SwiftMessages#471] opened 2021-06-08 06:33 UTC
When we try to build SwiftMessages with Xcode 13 beta, the following error is being thrown: `Enum cases with associated values cannot be marked potentially unavailable with '@available'`
<img width="1127" alt="Screenshot 2021-06-08 at 12 01 40 PM" src="https://user-images.githubusercontent.com/10910174/121134663-4a562d80-c851-11eb-8659-ede338abddfd.png">

**Comment by dneykov** [comment] 2021-06-08 10:48
Seems like a bug in Swift 5.5

https://bugs.swift.org/browse/SR-14539

**Comment by wtmoose** [comment] 2021-06-08 15:03
I'll keep an eye on this. Hopefully, they'll fix the bug!

**Comment by rizwan95** [comment] 2021-06-09 09:11
@wtmoose  @dneykov  There is no activity in the[ bug report](https://bugs.swift.org/browse/SR-14539) after it was reported or am I missing anything??

**Comment by racsol** [comment] 2021-06-15 09:36
Hi, do you have any hopes for the bug to be fixed by apple before iOS 15 release? the bug SR-14539 is marked as "Improvement" and without any activity for a long time...

**Comment by wtmoose** [comment] 2021-06-15 14:14
@racsol I have no idea

**Comment by rizwan95** [comment] 2021-06-17 11:09
My intuition says that Apple won't fix the bug sooner. What do we do?

**Comment by ymkim50** [comment] 2021-06-19 07:04
I temporarily downloaded the source.
And set Platform in Package.swift
platforms: [
         .iOS ("13.0")
     ],
It has been modified as

And added it as a Local Package. After that, no error occurred.

This is a temporary method.

**Comment by rizwan95** [comment] 2021-06-20 13:16
> I temporarily downloaded the source.
> And set Platform in Package.swift
> 
> platforms: [
> .iOS ("13.0")
> ],
> 
> And added it as a Local Package. After that, no error occurred.
> 
> This is a temporary method.

Yes that is one hackish solution...

**Comment by eigenl** [comment] 2021-06-29 17:09
Asked the author of that change about it:
https://twitter.com/slava_pestov/status/1409910935347732489?s=20

In short, the code needs to be updated not to require @available

I imagine something like

```
if #available(iOS 13, *) {
  struct WindowSceneCaseParams {
    let windowScene: UIWindowScene
    let windowLevel: UIWindow.Level
  }
#else 
  typealias WindowSceneCaseParams = Void
#endif

case windowScene(WindowSceneCaseParams)
```

or something similar could work as well? That way the case is always available.

**Comment by wtmoose** [comment] 2021-06-29 17:24
LOL...I'm not sure his suggestion would qualify as a workaround.

**Comment by wtmoose** [comment] 2021-06-29 17:43
@eigenl It seems you're trying to suggest a compile-time check but `available` is a run time thing. The code you're written `if #available...#else` isn't valid syntax and wouldn't compile.

If they're actually not going to fix this, then the only options I see are (a) make a breaking API change in SwiftUI or (b) stop supporting iOS 12 and below.

I'm inclined to take option (b).

**Comment by eigenl** [comment] 2021-06-29 18:44
Yeah, sorry for the brainfart. Removed it. Another passable solution would be

`case windowScene(_: Any, windowLevel: UIWindow.Level)`

and casting the associated value to UIWindowScene where needed (just one location in `SwiftMessages.Config+Extensions.swift`).

This does remove compile-time guarantee but requires no changes to applications and is the smallest change that could be made to fix it I believe. Dropping iOS 12 is certainly an option, but poses a problem for application developers where decisions  regarding minimum targets are out of their hands.

**Comment by rizwan95** [comment] 2021-06-30 06:58
I suppose the solution proposed by @eigenl should be good enough. What are your thoughts @wtmoose ?

**Comment by gereons** [comment] 2021-07-07 17:45
I reported the same issue in https://bugs.swift.org/browse/SR-14878 and that was just closed as "works as designed". Bummer.

**Comment by racsol** [comment] 2021-07-08 15:47
Any plans on fixing this issue? It seems that this will not be fixed in the swift project....

**Comment by rizwan95** [comment] 2021-07-14 05:34
> Yeah, sorry for the brainfart. Removed it. Another passable solution would be
> 
> `case windowScene(_: Any, windowLevel: UIWindow.Level)`
> 
> and casting the associated value to UIWindowScene where needed (just one location in `SwiftMessages.Config+Extensions.swift`).
> 
> This does remove compile-time guarantee but requires no changes to applications and is the smallest change that could be made to fix it I believe. Dropping iOS 12 is certainly an option, but poses a problem for application developers where decisions regarding minimum targets are out of their hands.

Can we go with this solution? This seems to be optimal. @wtmoose

**Comment by wtmoose** [comment] 2021-07-14 15:06
A quick fix using `case windowScene(_: Any, windowLevel: UIWindow.Level)` is on branch `work/9.0.4` for folks to try.

Version 10 will revert back to `case windowScene(_: UIWindowScene, windowLevel: UIWindow.Level)` and instead require iOS 13.

**Comment by acrabb** [comment] 2021-08-17 15:30
Any update on this?

**Comment by mzhangFE** [comment] 2021-08-30 03:18
We tried the latest version and still saw the same issue. The quick fix mentioned by @wtmoose worked. I may have missed something here but why could you make that as the official fix? Also some apps still support iOS 12 so dropping iOS 12 is not desired.

**Comment by giginet** [comment] 2021-09-12 11:20
I submitted PR to solve this issue. Please check it out!

https://github.com/SwiftKickMobile/SwiftMessages/pull/478

**Comment by rizwan95** [comment] 2021-09-15 18:58
Looks like the issue is solved with Xcode 13 RC.

**Comment by wtmoose** [comment] 2021-09-15 20:47
Woah, nice! I'll take a look when I get a chance to install the new build

**Comment by timonchev** [comment] 2021-09-16 07:47
@rizwan95 same issues in Xcode 13 RC too

**Comment by bogartpi** [comment] 2021-09-17 09:48
Any update on fixing this issue?

**Comment by racsol** [comment] 2021-09-17 09:51
@bogartpi the issue is fixed on branch 9.0.4. Does anyone know the released date of 9.0.4?

**Comment by Aidar** [comment] 2021-09-17 11:40
Please, release fix. We really need it. That is our single library that can't be build in Xcode 13.

**Comment by wtmoose** [comment] 2021-09-17 21:48
@rizwan95 9.0.4 released. Thanks!

**Closed by wtmoose** 2021-09-17 21:48 UTC

**Comment by rizwan95** [comment] 2021-09-19 07:16
Thanks a lot @wtmoose!
