### ISSUE TITLE
Error layout in iphone12 pro max , Iphone11pro max, Xs max

### ISSUE THREAD

**Issue by trinhson97** [SwiftKickMobile/SwiftMessages#457] opened 2021-02-25 07:57 UTC
layout Margin Additions displayed incorrectly on  iphone12 pro max , Iphone11pro max and iphone Xs max.
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-02-25 at 14 28 30](https://user-images.githubusercontent.com/39760540/109121380-bf599780-7779-11eb-92d2-4824b1b053d8.png)

**Comment by trinhson97** [comment] 2021-02-25 07:58
Here is the code used:

**Comment by trinhson97** [comment] 2021-02-25 07:59
let success = MessageView.viewFromNib(layout: .cardView)
        success.configureTheme(.success)
        success.configureDropShadow()
        success.configureContent(title: "Success", body: "Something good happened!")
        success.button?.isHidden = false
        
        var successConfig = SwiftMessages.defaultConfig
        successConfig.presentationStyle = .top
        successConfig.presentationContext = .window(windowLevel: UIWindow.Level.normal)
        SwiftMessages.show(config: successConfig, view: success)

**Comment by trinhson97** [comment] 2021-02-25 07:59
plz help me

**Comment by wtmoose** [comment] 2021-02-25 15:31
What do you want it to look like?

**Comment by trinhson97** [comment] 2021-02-26 06:48
I do want it to show as follows on screen ngang iphone xs max / iphone 11pro max : 
![Simulator Screen Shot - iPhone 11 Pro - 2021-02-26 at 13 43 16](https://user-images.githubusercontent.com/39760540/109265313-ef1ba480-7838-11eb-9313-280af7b3b40e.png)

**Comment by trinhson97** [comment] 2021-02-26 06:49
can you help me

**Comment by canhth** [comment] 2021-02-26 08:57
@wtmoose Let me clarify @trinhson97 question.

He's facing an issue in `landscape mode` with `CardView` on iPhone12 Pro Max, 11 Pro Max, Xs Max.

The `CornerRoundingView` frame should be updated when switching from Portrait to Landscape. In his case, the size still the same in both Portrait and Landscape mode.
_(It works with other iPhone type except `Pro Max` version)_

For @trinhson97, please create a Pull Request if you do know how to fix this issue.

**Comment by Kamui-IOS** [comment] 2021-02-26 09:35
i have the same problem.

**Comment by wtmoose** [comment] 2021-02-26 15:37
@canhth thank you.

This is behaving as designed. The Max phones are regular size class in landscape. SwiftMessages uses a different layout in regular size class because developers didn't want the messages to span across the entire screen on iPad. The regular size class layout uses the view's intrinsic width with a maximum width of 500pt @ 950 priority.

My suggestion is that folks stick with the current behavior. If not, my thoughts are:

1. App developers can add a width or minimum width constraint to `messageView.backgroundView` to preserve a desired width.
2. SwiftMessages could add an option to always use the compact size class layout. However, the option would be apply to iPad and Max phones. If app developers only want to apply the option to Max phones, they would be responsible for implementing that logic.

I am in the middle of a major layout system revamp (check out the head of `master`) that will gives app developers straight forward and powerful control of the message layout, so I'm not very interested in taking on (2) as a tangent.

I'm open to suggestions.

**Comment by trinhson97** [comment] 2021-02-28 03:28
@wtmoose thank you.

**Comment by trinhson97** [comment] 2021-02-28 04:02
Can you help me demo?

**Comment by wtmoose** [comment] 2021-02-28 17:58
@trinhson97 I don't understand what you're asking for

**Comment by trinhson97** [comment] 2021-03-01 02:03
can you demo help me add the minimum width or width constraint to messageView.backgroundView so the width becomes full screen on pro max devices ?

**Comment by wtmoose** [comment] 2021-03-11 20:39
No reply...closing

**Closed by wtmoose** 2021-03-11 20:39 UTC
