### ISSUE TITLE
swiftmessagesegue presenting overtop

### ISSUE THREAD

**Issue by Harryjeffs** [SwiftKickMobile/SwiftMessages#332] opened 2019-07-23 12:25 UTC
I was wondering if there is a fix for this; the darkened shadow for the actual view that was visible.

<img width="309" alt="Screen Shot 2019-07-23 at 10 23 11 pm" src="https://user-images.githubusercontent.com/18356889/61711908-8042b380-ad98-11e9-8890-c2b6d1e3e424.png">

This happens when another view is `present()`ed ontop of the swift segue. Is there anyway to stop this affect from happening or a work around to it at all? Dismissing the view will cause the presented view to dismiss as well. 

Presenting the VC again via the segue works however leaves the previous shadows in place, dismissing several views.

**Comment by wtmoose** [comment] 2019-07-23 13:52
This is a duplicate of #243. Can you change your topmost view controller's modal presentation style to `.overFullScreen`?

**Closed** 2019-09-17 16:37 UTC
