### ISSUE TITLE
SwiftMessages can only present a single custom alert and constraints become broken

### ISSUE THREAD

**Issue by danielsaidi** [SwiftKickMobile/SwiftMessages#433] opened 2020-11-04 09:12 UTC
[This commit](https://github.com/SwiftKickMobile/SwiftMessages/compare/8.0.3...master) causes strange UI glitches in our app. We use `SwiftMessages` to present custom alerts and with the changes in this PR, we can't present any alerts after closing the first one.

Also, when this happens, any view collections we push to the screen also get messed up, with their cells becoming tiny, like all constraints are broken.

This works in `8.0.3`.

**Comment by wtmoose** [comment] 2020-11-04 15:09
I haven't reproduced this in the demo app or my other test apps.

Got repro steps?

**Comment by danielsaidi** [comment] 2020-11-06 09:49
This happens in the main app of the company that I work for, so I unfortunately can't share any sample code. 

To sum up, we use SwiftMessages for custom alerts. After an alert has been shown, any subsequent alert presentations fail. Sometimes, this also messes up the constraints. For instance, this list:

![IMG_2894](https://user-images.githubusercontent.com/429927/98351691-565ce100-201d-11eb-9f2f-a978ccd72505.PNG)

fails to render correctly after an alert has been presented, and looks like this:

![IMG_2893](https://user-images.githubusercontent.com/429927/98351740-65dc2a00-201d-11eb-81a1-a7fe767e9cea.PNG)

I suspect that this line is what's causing it:

```
if let becomeKeyWindow = config.becomeKeyWindow { return becomeKeyWindow }
```

I could create a fork and verify this.

**Comment by wtmoose** [comment] 2020-11-06 15:45
Are you setting `config.becomeKeyWindow`? The change on that line of code only affects the case where you've set `config.becomeKeyWindow = false`. Otherwise, the change would have no effect – you can verify this yourself by inspecting the logic.

**Comment by wtmoose** [comment] 2020-11-24 20:29
Closing since there hasn't been any followup in weeks.

**Closed by wtmoose** 2020-11-24 20:29 UTC
