### ISSUE TITLE
'SwiftMessages.Swift' found superclass with type 'BaseView'

### ISSUE THREAD

**Issue by Gulshan1993** [SwiftKickMobile/SwiftMessages#452] opened 2021-01-20 06:02 UTC
'MessageView' has different definitions in different modules; the first difference is a definition in module 'SwiftMessages.Swift' found superclass with type 'BaseView'

if anybody faces this issue in the Xcode 12.0
please use this and fix this issue.
![Screenshot 2021-01-20 at 11 21 41 AM](https://user-images.githubusercontent.com/72385081/105133618-1339e680-5b13-11eb-8774-83b52170c599.png)
 project.
Please

**Comment by wtmoose** [comment] 2021-01-20 15:05
This is a duplicate of #420

**Closed by wtmoose** 2021-01-20 15:05 UTC
