### ISSUE TITLE
titleLabel behaviour inconsistent 

### ISSUE THREAD

**Issue by Muarl** [SwiftKickMobile/SwiftMessages#19] opened 2016-09-24 09:08 UTC
See following example:

```
SwiftMessages.show {
    let view = MessageView.viewFromNib(layout: .MessageView)
    view.configureTheme(.info)
    view.titleLabel = nil
    view.configureContent(body: "Some Text!")
    return view
}
```

Result -> A title with "[Title]" content is shown

```
SwiftMessages.show {
    let view = MessageView.viewFromNib(layout: .MessageView)
    view.configureTheme(.info)
    view.titleLabel?.text = nil
    view.configureContent(body: "Some Text!")
    return view
}
```

Result -> No title is shown

**Comment by wtmoose** [comment] 2016-09-24 15:25
Hi. This is behaving as intended. A goal for SwiftMessages is to be highly flexible by minimizing internal logic. When you set `view.titleLabel = nil` that doesn't automatically remove the label from the view hierarchy. If it did, then it would follow that setting `view.titleLabel = something` should add `something` into the view hierarchy. And that would both add complexity and remove flexibility.

There are two recommended ways to customize what elements are displayed:

1. Copy the nib file into your project and delete elements you don't want.
2. Hide unwanted elements, e.g. `view.titleLabel?.hidden = true`. (Stack views are smart about ignoring hidden elements in the layout.)

**Comment by cooler333** [comment] 2016-10-03 16:33
Weird behaviour

**Comment by wtmoose** [comment] 2016-10-05 02:30
Open to discussion on this, but closing for now since there haven't been any constructive comments after 10 days.

**Closed by wtmoose** 2016-10-05 02:30 UTC

**Comment by cooler333** [comment] 2016-10-05 08:57
```swift
// Show only title(or body) label 
view.configureContent(body: title)

// Show all labels
view.configureContent(title: "Error", body: title)

// Show all labels and button
configureContent(title: title, body: subtitle, buttonTitle: "Close")
```
