### ISSUE TITLE
Wrong image bundle

### ISSUE THREAD

**Issue by mo3bius** [SwiftKickMobile/SwiftMessages#102] opened 2017-07-06 08:41 UTC
Hi, I've noticed that every time I run 'pod install' the bundle of images.xcassets changes to SwiftMessages-SwiftMessages and no longer finds the error icon so the app crashes. While I was watching I found a ! in these lines of code: 
```
     public var image: UIImage {        
        return UIImage(named: rawValue, in: Bundle.sm_frameworkBundle(), compatibleWith: nil)!
     }
```
So in my case with the wrong bundle the app goes out. It's very annoying because as I said every time I run pod install I have to change the bundle. 
Please solve it

**Comment by wtmoose** [comment] 2017-07-07 14:55
I'm so sorry that you've been annoyed by SwiftMessages, Luigi. Let's see if I can help!

Given that other's aren't having this problem, maybe there's something wrong on your end. Are you on the minimum required version of CocoaPods 1.1.0 or later? Are you using any betas (OS X, Xcode, CocoaPods, etc.)? What does your Podfile look like?

Note that I don't control how CocoaPods generates the bundle, so if none of thing obvious things help, you may need to seek help from the CocoaPods team.

**Comment by cojalvo** [comment] 2017-07-07 20:01
Hi, having the same problem. and using  CocoaPods 1.3.0

**Comment by wtmoose** [comment] 2017-07-07 20:18
@cojalvo CocoaPods 1.3.0 is still in beta.

**Comment by cojalvo** [comment] 2017-07-07 20:32
so which version to use?
cause its crashing.

**Comment by wtmoose** [comment] 2017-07-07 20:34
SwiftMessages requires minimum CocoaPods 1.1.0.

**Comment by cojalvo** [comment] 2017-07-07 21:05
Update to  CocoaPods 1.1.0 but still crashing.
Could not load the "errorIcon" image referenced from a nib in the bundle with identifier "org.cocoapods.SwiftMessages"

**Comment by wtmoose** [comment] 2017-07-07 21:07
Sounds suspiciously like your clean process didn't work. Try deleting derived data.

**Comment by wtmoose** [comment] 2017-07-07 21:08
Also, it is a known issue that this doesn't work on a jailbroken device.

**Comment by cojalvo** [comment] 2017-07-07 21:09
my device is not jailbroken i will try to deleting derived data.

**Comment by wtmoose** [comment] 2017-07-09 16:21
@mo3bius I spent some time looking at this using both CocoPods 1.2.1 and 1.3.0-beta2 and I can't reproduce.

Can you post a project for me to inspect? I've attached a sample project you can use. And let me know your environment, e.g. Xcode version, CocoaPods version, etc.

[SMTest.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/1133885/SMTest.zip)

**Comment by wtmoose** [comment] 2017-07-17 00:47
Closing due to no reply from poster.

**Closed by wtmoose** 2017-07-17 00:47 UTC

**Comment by gabrieloliva** [comment] 2017-08-23 19:57
This is happening while changing from Xcode versions (I was testing some features in Swift 3.2 with Xcode 9 beta).

Once I deleted all my derived data, it all started to work fine.

I didn't investigate what is going on, but since we'll start to use new release from Xcode, may be I'll can look around.
