### ISSUE TITLE
iOS13.1.3 compatibility issue

### ISSUE THREAD

**Issue by woohyuknrg** [SwiftKickMobile/SwiftMessages#360] opened 2019-10-25 07:14 UTC
when message show on my iPad Pro(11-inch), the whole UI doesn't respond to touch event; but it's OK on iOS13.1 simulator. The code below: 

var config = SwiftMessages.defaultConfig
config.presentationContext = .window(windowLevel: .normal)
config.preferredStatusBarStyle = .lightContent
config.duration = .seconds(seconds: 3)

SwiftMessages.show(config: config)

**Comment by wtmoose** [comment] 2019-10-25 14:09
I wasn't able to reproduce this on my iPhone running 13.1 using the Explore section of the Demo app. Does the demo app not work for you?

Not much I can do without repro steps. If you can, send me a small sample app that doesn't work.

**Comment by woohyuknrg** [comment] 2019-10-25 14:55
I run the SwiftMessages demo, has the same issue.
I debug the source code, something wrong in PassthroughWindow:
`override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        let view = super.hitTest(point, with: event)
        return view == self ? nil : view
    }`

in iOS13.1.3 iPad Pro device, when message show, touch other place, it return view; 
but in iOS 13.1 simulator, it return nil, so I can touch anywhere.

**Comment by woohyuknrg** [comment] 2019-10-25 15:52
You can reproduce on iPad Pro (11-inch) 13.1 simulator, or iPad Pro (12.9-inch) (3rd generation) 13.1 simulator.
Works well on iPad Pro (9.7-inch) 13.1 or below, weird

**Comment by wtmoose** [comment] 2019-10-25 16:06
Didn't you initially say it was OK in simulator but broken on device? Unfortunately, my iPad Pro is already on 13.2.

**Comment by woohyuknrg** [comment] 2019-10-25 16:28
Before i only tested on 9.7 inch ipad pro simulator, it's OK on it. Now i test on all ipad pro simulator. OK on 9.7 and 10.5, have problem on 11 and 12.9. You can use 11 simulator to reproduce. Thanks

**Comment by wtmoose** [comment] 2019-10-27 21:45
I'm on Xcode 13.2 beta, but I can't reproduce on iPad Pro 11 Simulator. Am I doing something wrong in the attached video?

[iPad Pro 11 inch simulator demo.mp4.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/3776460/iPad.Pro.11.inch.simulator.demo.mp4.zip)

**Comment by woohyuknrg** [comment] 2019-10-28 01:32
Layout select Card, when message show, try to scroll the view below message view

**Comment by wtmoose** [comment] 2019-10-28 02:57
Works for me.

[iPad Pro 11 inch demo 2.mp4.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/3776930/iPad.Pro.11.inch.demo.2.mp4.zip)

**Comment by woohyuknrg** [comment] 2019-10-28 03:00
presentationContext set to normal level

**Comment by wtmoose** [comment] 2019-10-28 06:41
OK my bad. Looks like iOS has started inserting its own views into the window's hierarchy.

Fix is on the head of `master` branch. I'll release soon.

**Comment by woohyuknrg** [comment] 2019-10-28 07:06
Thank you very much

**Comment by woohyuknrg** [comment] 2019-11-11 01:31
Hi, when does next version release?

**Comment by wtmoose** [comment] 2019-11-11 01:56
As soon as I get some free time

**Comment by ullstrm** [comment] 2019-12-05 10:48
Hi @wtmoose ! We have this problem aswell for our iPads! There seems to be a commit that should fix this on the master-branch. Is it ready for production? Will there be a release for this soon or are there other issues that needs fixing?

**Comment by BinaryDennis** [comment] 2019-12-12 16:13
I would really appreciate it if this issue could be solved soon.

**Comment by nectar1** [comment] 2020-03-02 15:13
Up

**Comment by d4rkd3v1l** [comment] 2020-03-30 10:05
Is there a timeline, when this will be released officially?

**Comment by wtmoose** [comment] 2020-07-09 19:13
Included in 8.0.0 release

**Closed by wtmoose** 2020-07-09 19:13 UTC
