### ISSUE TITLE
Can you support swift package manager?

### ISSUE THREAD

**Issue by CainLuo** [SwiftKickMobile/SwiftMessages#387] opened 2020-04-15 09:17 UTC
Can you support swift package manager?

**Comment by wtmoose** [comment] 2020-04-15 14:13
Dupe of #330 

Support for resources isn't coming until Swift 5.3.

https://forums.swift.org/t/se-0271-package-manager-resources/30730/74

**Closed by wtmoose** 2020-04-15 14:13 UTC

**Comment by knothed** [comment] 2020-06-15 15:20
@CainLuo See here for a working solution: https://github.com/SwiftKickMobile/SwiftMessages/pull/395
