### ISSUE TITLE
Crash on jailbroken device loading image from nib

### ISSUE THREAD

**Issue by androidcn** [SwiftKickMobile/SwiftMessages#12] opened 2016-09-05 12:59 UTC
Could not load the "errorIcon" image referenced from a nib in the bundle with identifier "org.cocoapods.SwiftMessages"
fatal error: unexpectedly found nil while unwrapping an Optional value

also clean build .... not work

**Comment by androidcn** [comment] 2016-09-05 14:20
iOS 9.3.3
also i run demo Project on my device.

same problem 

CoreFoundation = 1290.110000
Could not match CoreFoundation = 1290.110000
2016-09-05 22:19:43.300 Demo[49264:2901168] Could not load the "errorIcon" image referenced from a nib in the bundle with identifier "org.cocoapods.SwiftMessages"
fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by wtmoose** [comment] 2016-09-06 01:47
Could you answer a few questions:

1. What device?
2. Is the device jailbroken?
3. Have you tried a different device type and/or iOS version?

**Comment by androidcn** [comment] 2016-09-06 01:49
9.3.3
6s Plus
jailbroken

simulator is normal

i will try iPhone 5s later

**Comment by wtmoose** [comment] 2016-09-06 01:53
See #9. App in store only crashing on a single device. Waiting to find out if the device is jailbroken.

**Comment by wtmoose** [comment] 2016-09-06 02:22
Also, could you try `ErrorView`, `TabView` and `CardView` nibs and let me know if they all crash?

**Comment by androidcn** [comment] 2016-09-06 02:48
https://github.com/CocoaPods/CocoaPods/issues/1546

**Comment by wtmoose** [comment] 2016-09-06 13:58
The links you posted don't seem relevant.

As noted in #9, this appears to be an issue with jailbroken devices running iOS 9.3.3. I don't have a jailbroken device or iOS 9.3.3, so there isn't much I can do at the moment.

It would be very helpful if you could look for a workaround on your end. I created a branch called `jailbreak1` with a possible workaround: replace errorIcon.pdf with errorIcon*.png. Could you take a look? Anything else you'd like to try is appreciated.

**Comment by androidcn** [comment] 2016-09-07 07:54
jailbreak 1 or 2?

**Comment by wtmoose** [comment] 2016-09-07 10:11
Jailbreak1

**Comment by wtmoose** [comment] 2016-09-14 15:16
Closing as duplicate of #9.

**Closed by wtmoose** 2016-09-14 15:16 UTC
