### ISSUE TITLE
SwiftMessage not covering status bar in iOS 13

### ISSUE THREAD

**Issue by sbrioux** [SwiftKickMobile/SwiftMessages#373] opened 2020-01-10 19:47 UTC
So I am noticing currently in my app, the SwiftMessage isn't covering the status bar fully on iOS 13.  Also to note is that the app does have dark mode disabled using the plist configuration.

The issue is mostly noticeable on iOS devices with out the notch.  The screen shot is from an iPhone 8

iOS 13.3.1
![image](https://user-images.githubusercontent.com/4192331/72181585-ae07cd00-33b7-11ea-9daf-e3c66487d914.png)

The following is the code I am using to display the message.
```swift
            let msgView = MessageView.viewFromNib(layout: .statusLine)
            msgView.backgroundView.backgroundColor = .white
            msgView.bodyLabel?.textColor = .black
            msgView.configureContent(body: "NO_INET".localized())

            var config = SwiftMessages.defaultConfig
            config.duration = .forever
            config.presentationContext = .window(windowLevel: .statusBar)
            config.preferredStatusBarStyle = .lightContent

            SwiftMessages.show(config: config, view: msgView)
```

Did I do something wrong or is this a bug?

**Comment by wtmoose** [comment] 2020-01-10 20:24
Dupe of #368

**Closed by wtmoose** 2020-01-10 20:24 UTC
