### ISSUE TITLE
Crash: Fatal Exception: NSGenericException

### ISSUE THREAD

**Issue by ravindrashetty** [SwiftKickMobile/SwiftMessages#367] opened 2019-12-16 10:54 UTC
Seeing this crash on recent releases. Details Below.

**Crash Description:**

`Unable to activate constraint with anchors <NSLayoutYAxisAnchor:0x1049d7540 "SwiftMessages.MaskingView:0x10cd1ffe0.bottom"> and <NSLayoutYAxisAnchor:0x1049d2bf0 "UITabBar:0x10a4e3a00.top"> because they have no common ancestor. Does the constraint or its anchors reference items in different view hierarchies? That's illegal.`

**Stack trace:**
>Fatal Exception: NSGenericException
0  CoreFoundation                 0x18283ad8c __exceptionPreprocess
1  libobjc.A.dylib                0x1819f45ec objc_exception_throw
2  CoreFoundation                 0x18283ac6c -[NSException initWithCoder:]
3  Foundation                     0x183186c5c -[NSLayoutConstraint _setActive:mutuallyExclusiveConstraints:]
4  SwiftMessages                  0x103963b04 installMaskingView #1 (containerView:) in Presenter.install() (Presenter.swift:351)
5  SwiftMessages                  0x1039632ac Presenter.install() (Presenter.swift:417)
6  SwiftMessages                  0x103960dd4 Presenter.show(completion:) (Presenter.swift:116)
7  SwiftMessages                  0x10396a720 closure #1 in SwiftMessages.dequeueNext() (SwiftMessages.swift:560)
8  SwiftMessages                  0x10395c38c thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>)

**Comment by wtmoose** [comment] 2019-12-16 15:28
This is a duplicate of #348.

So far nobody has provided reproduction steps, so I there's not much I can do. If you can help me reproduce, I'll take a look.

**Closed by wtmoose** 2019-12-16 15:28 UTC
