### ISSUE TITLE
Crashing at SwiftMessages.Config() or SwiftMessags.defaultConfig version 7.0.1

### ISSUE THREAD

**Issue by Nathan2017** [SwiftKickMobile/SwiftMessages#423] opened 2020-10-12 16:53 UTC
![Screen Shot 2020-10-13 at 12 50 57 AM](https://user-images.githubusercontent.com/25632519/95771751-29533200-0cee-11eb-94c5-f024eafe384d.png)

version 5.0.1 working fine but when upgrading to 7.0.1 instantiate SwiftMessages.Config() or SwiftMessages.defaultConfig caused retain cycle. Hope someone can help me thank you.

**Comment by wtmoose** [comment] 2020-10-12 17:07
Sounds like you need to clean your derived data. Also, why aren't you upgrading to version 8?

**Comment by Nathan2017** [comment] 2020-10-12 17:41
> Sounds like you need to clean your derived data. Also, why aren't you upgrading to version 8?

Already clean the derived data and also upgrading to version 8 , still getting the retain cycle crash

**Comment by wtmoose** [comment] 2020-10-12 17:43
Nobody else is having this issue, so I need more to go on. What do you mean by "retain cycle crash"?

**Comment by Nathan2017** [comment] 2020-10-12 17:54
![Screen Shot 2020-10-13 at 1 52 12 AM](https://user-images.githubusercontent.com/25632519/95776387-cca84500-0cf6-11eb-8543-18d85258a38d.png)
![Screen Shot 2020-10-13 at 1 51 57 AM](https://user-images.githubusercontent.com/25632519/95776398-d29e2600-0cf6-11eb-9ea3-6c86830e85cb.png)
Setting up the config seem to fix the problem but now there is an error on windowviewcontroller

**Comment by Nathan2017** [comment] 2020-10-12 18:03
![Screen Shot 2020-10-13 at 2 01 58 AM](https://user-images.githubusercontent.com/25632519/95777082-16455f80-0cf8-11eb-9920-a925b5c3447e.png)
Its kind of weird that if i comment out the setup just instantiate the SwiftMessages.Config() i will get swift_retain error

**Comment by wtmoose** [comment] 2020-10-12 18:17
I've never seen `swift_retain` and I don't see much online. Are you compiling with some non-default config? Did you check if you get this in the Demo app? If you can help me reproduce the problem, I can take a look. A sample project would be super helpful.

**Comment by Drusy** [comment] 2020-10-21 07:22
I've got this issue switch from `7.0` to `work/xcode12` for SPM migration. Clean build helped.

**Comment by wtmoose** [comment] 2020-10-25 21:25
Try 8.0.3

**Comment by wtmoose** [comment] 2020-12-16 19:26
Closing. No reply since my last suggestion.

**Closed by wtmoose** 2020-12-16 19:26 UTC

**Comment by RaghavaNaidu46** [comment] 2021-05-30 14:36
<img width="1668" alt="Screen Shot 2021-05-30 at 8 02 12 PM" src="https://user-images.githubusercontent.com/12371030/120108243-f036d780-c181-11eb-90c8-40d26ae53087.png">

I've gone through the thread, but no solution was found. I'm using the latest version(9.0.2). Also cleared derived data and did project clean. 

FYI: Your demo project with the same line work perfectly.

kindly help me with the same.

**Comment by wtmoose** [comment] 2021-05-30 18:17
@RaghavaNaidu46 this is going to be an issue with your project configuration, not SwiftMessages itself. Now are you installing SwiftMessages, e.g. CocoaPods, Carthage, Swift Package Manager?

**Comment by RaghavaNaidu46** [comment] 2021-05-31 02:49
CocoaPods

**Comment by RaghavaNaidu46** [comment] 2021-06-02 06:09
@wtmoose Any update for me...

**Comment by jhfkf** [comment] 2021-06-07 09:25
same problem

**Comment by jhfkf** [comment] 2021-06-07 09:41
emmm...  
change 
`public struct Config`
to 
`public class Config`
everthing will be ok

**Comment by jhfkf** [comment] 2021-06-07 09:47
so weird! crashing will appear in one project...

**Comment by wtmoose** [comment] 2021-06-07 13:32
@RaghavaNaidu46 I suggest looking through the list of `EXC_BAD_ACCESS` issues that have been filed:

https://github.com/SwiftKickMobile/SwiftMessages/issues?q=is%3Aissue+exc_bad_access

I believe the most common problem is wrong Swift version. If none of this helps, I really have no idea how to help without reproduction steps or a sample project. This might be a good one to post on StackOverflow.

**Comment by RaghavaNaidu46** [comment] 2021-06-15 05:28
As I told above, it works perfectly within a new project. Will try again to reproduce the issue and share the POC here.

**Comment by RaghavaNaidu46** [comment] 2021-06-16 06:25
> @RaghavaNaidu46 I suggest looking through the list of `EXC_BAD_ACCESS` issues that have been filed:
> 
> https://github.com/SwiftKickMobile/SwiftMessages/issues?q=is%3Aissue+exc_bad_access
> 
> I believe the most common problem is wrong Swift version. If none of this helps, I really have no idea how to help without reproduction steps or a sample project. This might be a good one to post on StackOverflow.

@wtmoose  Yes, it's because of an unspecified swift version. Thanks, brother.

**Comment by wtmoose** [comment] 2021-06-16 14:43
Nice
