### ISSUE TITLE
Error when try to install using Pods

### ISSUE THREAD

**Issue by engmsaleh** [SwiftKickMobile/SwiftMessages#13] opened 2016-09-08 14:15 UTC
I got the following error
[!] Unable to find a specification for `SwiftMessages`

**Comment by wtmoose** [comment] 2016-09-08 14:45
This is a duplicate of #11.

I don't see how I can be of help here since SwiftMessages definitely in the CocoaPods repo. See my comments in #11.

**Closed by wtmoose** 2016-09-08 14:45 UTC
