### ISSUE TITLE
Message View Width not adjust according to screenWidth on landscape mode?

### ISSUE THREAD

**Issue by Lokeshgupta25** [SwiftKickMobile/SwiftMessages#391] opened 2020-04-24 12:39 UTC
When i change our app mode from portrait to landscape mode swiftmessages width not adjust to full width of screen . How can i solve this?

i am using follwing code...

       var alertConfig = SwiftMessages.defaultConfig
        alertConfig.presentationStyle = .top
        alertConfig.prefersStatusBarHidden = true
        
        alertConfig.presentationContext = .window(windowLevel: UIWindow.Level.statusBar)
        alertConfig.duration = .seconds(seconds: 2.0)
        alertConfig.shouldAutorotate = true
        let alertView = MessageView.viewFromNib(layout: .messageView)
        alertView.button?.isHidden = true
        alertView.configureBackgroundView(width:1000)
        alertView.configureDropShadow()
        alertView.titleLabel?.font = UIFont.systemFont(ofSize: 14.0, weight: UIFont.Weight.regular)
        alertView.bodyLabel?.text = message
        alertView.bodyLabel?.font = UIFont.systemFont(ofSize: 14.0, weight: UIFont.Weight.regular)
        alertView.configureContent(title: title.rawValue, body: message)

In portrait mode
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-24 at 18 12 23](https://user-images.githubusercontent.com/47971613/80213490-deb5fe80-8656-11ea-8ba2-82dfdb02d2b3.png)

On in Landscape mode...
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-24 at 18 12 17](https://user-images.githubusercontent.com/47971613/80213397-bcbc7c00-8656-11ea-8286-983c5a99a12f.png)

**Comment by wtmoose** [comment] 2020-04-24 13:26
That isn't normal. I'd remove

````swift
alertView.configureBackgroundView(width:1000)
````

It isn't needed.

**Comment by Lokeshgupta25** [comment] 2020-04-24 13:32
alertView.configureBackgroundView(width:1000)
its working same after removing this also

**Comment by wtmoose** [comment] 2020-04-24 13:37
Can you reproduce it in the demo app?

**Comment by Lokeshgupta25** [comment] 2020-04-24 13:40
ya sure

**Comment by Lokeshgupta25** [comment] 2020-04-24 13:48
[demo.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/4529205/demo.zip)

Please follow the follwing step:
App launch on Portrait mode -> click on button for showing Alert -> Change App mode to Landscape ->  click on button for showing Alert

**Comment by wtmoose** [comment] 2020-04-24 14:08
It works for me. Your environment must be different. I'm using:

Xcode 11.4.1
iPhone 11 Pro simulator

![Rotate](https://user-images.githubusercontent.com/2529176/80221440-eb146a00-860a-11ea-8c9b-35c8f5e85ed6.gif)

**Comment by Lokeshgupta25** [comment] 2020-04-24 14:22
No Please Switch app on landscape mode when portrait mode alert have dismiss.

**Comment by wtmoose** [comment] 2020-04-24 14:53
Oh, this is related to the new scene stuff in iOS 13. You need to use the head of the master branch. I have a backlog of fixes to release including the fix for this issue.

**Comment by Lokeshgupta25** [comment] 2020-04-24 14:59
Can you elaborate it more how can I resolve this issue ASAP.
Thanks

**Comment by wtmoose** [comment] 2020-04-24 15:00
You need to use the head of the master branch.

**Comment by Lokeshgupta25** [comment] 2020-04-24 15:09
have you fixed this issue or you are going to fix this issue?

**Comment by wtmoose** [comment] 2020-07-09 19:12
Included in 8.0.0 release

**Closed by wtmoose** 2020-07-09 19:12 UTC
